In [43]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder




import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.sentiment import SentimentIntensityAnalyzer
import string

# Download NLTK resources (if not already downloaded)
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('vader_lexicon')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...

True

In [2]:
df = pd.read_csv("fake_job_postings.csv")

In [3]:
df.head(10)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0
5,6,Accounting Clerk,"US, MD,",NaN,NaN,NaN,Job OverviewApex is an environmental consultin...,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,0
6,7,Head of Content (m/f),"DE, BE, Berlin",ANDROIDPIT,20000-28000,"Founded in 2009, the Fonpit AG rose with its i...",Your Responsibilities: Manage the English-spea...,Your Know-How: ...,Your Benefits: Being part of a fast-growing co...,0,1,1,Full-time,Mid-Senior level,Master's Degree,Online Media,Management,0
7,8,Lead Guest Service Specialist,"US, CA, San Francisco",NaN,NaN,Airenvy’s mission is to provide lucrative yet ...,Who is Airenvy?Hey there! We are seasoned entr...,"Experience with CRM software, live chat, and p...",Competitive Pay. You'll be able to eat steak e...,0,1,1,NaN,NaN,NaN,NaN,NaN,0
8,9,HP BSM SME,"US, FL, Pensacola",NaN,NaN,Solutions3 is a woman-owned small business who...,Implementation/Configuration/Testing/Training ...,MUST BE A US CITIZEN.An active TS/SCI clearanc...,NaN,0,1,1,Full-time,Associate,NaN,Information Technology and Services,NaN,0
9,10,Customer Service Associate - Part Time,"US, AZ, Phoenix",NaN,NaN,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 6 months custo...,NaN,0,1,0,Part-time,Entry level,High School or equivalent,Financial Services,Customer Service,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  object
 2   location             17534 non-null  object
 3   department           6333 non-null   object
 4   salary_range         2868 non-null   object
 5   company_profile      14572 non-null  object
 6   description          17879 non-null  object
 7   requirements         15184 non-null  object
 8   benefits             10668 non-null  object
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  object
 13  required_experience  10830 non-null  object
 14  required_education   9775 non-null   object
 15  industry             12977 non-null  object
 16  function             11425 non-null  object
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), object(13)
memory usage: 2.5+ MB

In [5]:
#check for duplicates
df.duplicated().sum()

0

In [6]:
df['country_abb'] = df['location'].str.split(',', expand = True)[0]

In [7]:
df['country_abb'].unique()

array(['US', 'NZ', 'DE', 'GB', 'AU', 'SG', 'IL', 'AE', 'CA', 'IN', 'EG',
       'PL', 'GR', nan, 'PK', 'BE', 'BR', 'SA', 'DK', 'RU', 'ZA', 'CY',
       'HK', 'TR', 'IE', 'LT', 'JP', 'NL', 'AT', 'KR', 'FR', 'EE', 'TH',
       'PA', 'KE', 'MU', 'MX', 'RO', 'MY', 'FI', 'CN', 'ES', 'SE', 'CL',
       'UA', 'QA', 'IT', 'LV', 'IQ', 'BG', 'PH', 'CZ', 'VI', 'MT', 'HU',
       'BD', 'KW', 'LU', 'NG', 'RS', 'BY', 'VN', 'ID', 'ZM', 'NO', 'BH',
       'UG', 'CH', 'TT', 'SD', 'SK', 'AR', 'TW', 'PT', 'PE', 'CO', 'IS',
       'SI', 'MA', 'AM', 'TN', 'GH', 'AL', 'HR', 'CM', 'SV', 'NI', 'LK',
       'JM', 'KZ', 'KH'], dtype=object)

In [8]:
df.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,country_abb
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0,US
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,NZ
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0,US
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,US
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,US

In [9]:
country_dictionary = {
    'US': 'United States',
    'NZ': 'New Zealand',
    'DE': 'Germany',
    'GB': 'United Kingdom',
    'AU': 'Australia',
    'SG': 'Singapore',
    'IL': 'Israel',
    'AE': 'United Arab Emirates',
    'CA': 'Canada',
    'IN': 'India',
    'EG': 'Egypt',
    'PL': 'Poland',
    'GR': 'Greece',
    'PK': 'Pakistan',
    'BE': 'Belgium',
    'BR': 'Brazil',
    'SA': 'Saudi Arabia',
    'DK': 'Denmark',
    'RU': 'Russia',
    'ZA': 'South Africa',
    'CY': 'Cyprus',
    'HK': 'Hong Kong',
    'TR': 'Turkey',
    'IE': 'Ireland',
    'LT': 'Lithuania',
    'JP': 'Japan',
    'NL': 'Netherlands',
    'AT': 'Austria',
    'KR': 'South Korea',
    'FR': 'France',
    'EE': 'Estonia',
    'TH': 'Thailand',
    'PA': 'Panama',
    'KE': 'Kenya',
    'MU': 'Mauritius',
    'MX': 'Mexico',
    'RO': 'Romania',
    'MY': 'Malaysia',
    'FI': 'Finland',
    'CN': 'China',
    'ES': 'Spain',
    'SE': 'Sweden',
    'CL': 'Chile',
    'UA': 'Ukraine',
    'QA': 'Qatar',
    'IT': 'Italy',
    'LV': 'Latvia',
    'IQ': 'Iraq',
    'BG': 'Bulgaria',
    'PH': 'Philippines',
    'CZ': 'Czech Republic',
    'VI': 'U.S. Virgin Islands',
    'MT': 'Malta',
    'HU': 'Hungary',
    'BD': 'Bangladesh',
    'KW': 'Kuwait',
    'LU': 'Luxembourg',
    'NG': 'Nigeria',
    'RS': 'Serbia',
    'BY': 'Belarus',
    'VN': 'Vietnam',
    'ID': 'Indonesia',
    'ZM': 'Zambia',
    'NO': 'Norway',
    'BH': 'Bahrain',
    'UG': 'Uganda',
    'CH': 'Switzerland',
    'TT': 'Trinidad and Tobago',
    'SD': 'Sudan',
    'SK': 'Slovakia',
    'AR': 'Argentina',
    'TW': 'Taiwan',
    'PT': 'Portugal',
    'PE': 'Peru',
    'CO': 'Colombia',
    'IS': 'Iceland',
    'SI': 'Slovenia',
    'MA': 'Morocco',
    'AM': 'Armenia',
    'TN': 'Tunisia',
    'GH': 'Ghana',
    'AL': 'Albania',
    'HR': 'Croatia',
    'CM': 'Cameroon',
    'SV': 'El Salvador',
    'NI': 'Nicaragua',
    'LK': 'Sri Lanka',
    'JM': 'Jamaica',
    'KZ': 'Kazakhstan',
    'KH': 'Cambodia'
}

In [10]:
#Create Country column and fill the country names using the country_dictionary
for key, value in country_dictionary.items():
    df.loc[df['country_abb'] == key, 'country'] = value

In [11]:
df.head(2)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,country_abb,country
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0,US,United States
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,NZ,New Zealand

In [13]:
len((df['department'].unique()))

1338

In [14]:
#drop department, title, location column
df.drop(columns = ['department','title','location'], inplace = True)

In [15]:
df

,job_id,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,country_abb,country
0,1,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0,US,United States
1,2,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,NZ,New Zealand
2,3,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0,US,United States
3,4,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,US,United States
4,5,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,US,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0,CA,Canada
17876,17877,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0,US,United States
17877,17878,NaN,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0,US,United States
17878,17879,NaN,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0,NG,Nigeria
17879,17880,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0,NZ,New Zealand

In [25]:
#Merge Columns company_profile,description,requirements and benefits as Language_processing(LP) and drop orginal columns
df['LP'] = df['company_profile'].fillna('')+' '+df['requirements'].fillna('')+' '+df['description'].fillna('')+' '+df['benefits'].fillna('')+' '
df = df.drop(columns = ['company_profile','description','requirements','benefits'], axis = 1)

In [26]:
df.head()

,job_id,salary_range,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,country_abb,country,LP
0,1,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0,US,United States,"We're Food52, and we've created a groundbreaki..."
1,2,NaN,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,NZ,New Zealand,"90 Seconds, the worlds Cloud Video Production ..."
2,3,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0,US,United States,Valor Services provides Workforce Solutions th...
3,4,NaN,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,US,United States,Our passion for improving quality of life thro...
4,5,NaN,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,US,United States,SpotSource Solutions LLC is a Global Human Cap...

In [33]:

# Initialize WordNet Lemmatizer
lemmatizer = WordNetLemmatizer()

# Define function for text preprocessing
def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()
    
    # Remove punctuations
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    # Tokenize text into words
    tokens = word_tokenize(text)
    
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]
    
    # Lemmatize words to their base form
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    
    # Join tokens back into a single string
    preprocessed_text = ' '.join(tokens)
    
    return preprocessed_text

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [36]:
# Apply preprocessing function to a DataFrame column
df['preprocessed_column'] = df['LP'].map(preprocess_text)

In [37]:
df

,job_id,salary_range,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,country_abb,country,LP,preprocessed_column
0,1,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0,US,United States,"We're Food52, and we've created a groundbreaki...",food52 weve created groundbreaking awardwinnin...
1,2,NaN,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,NZ,New Zealand,"90 Seconds, the worlds Cloud Video Production ...",90 second world cloud video production service...
2,3,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0,US,United States,Valor Services provides Workforce Solutions th...,valor service provides workforce solution meet...
3,4,NaN,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,US,United States,Our passion for improving quality of life thro...,passion improving quality life geography heart...
4,5,NaN,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,US,United States,SpotSource Solutions LLC is a Global Human Cap...,spotsource solution llc global human capital m...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0,CA,Canada,Vend is looking for some awesome new talent to...,vend looking awesome new talent come join u yo...
17876,17877,NaN,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0,US,United States,WebLinc is the e-commerce platform and service...,weblinc ecommerce platform service provider fa...
17877,17878,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0,US,United States,We Provide Full Time Permanent Positions for m...,provide full time permanent position many medi...
17878,17879,NaN,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0,NG,Nigeria,1. Must be fluent in the latest versions of C...,1 must fluent latest version corel amp adobe c...
17879,17880,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0,NZ,New Zealand,Vend is looking for some awesome new talent to...,vend looking awesome new talent come join u yo...

In [38]:
#drop
df.drop(columns =  "LP", axis = 1, inplace = True)

In [39]:
df

,job_id,salary_range,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,country_abb,country,preprocessed_column
0,1,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0,US,United States,food52 weve created groundbreaking awardwinnin...
1,2,NaN,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,NZ,New Zealand,90 second world cloud video production service...
2,3,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0,US,United States,valor service provides workforce solution meet...
3,4,NaN,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,US,United States,passion improving quality life geography heart...
4,5,NaN,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,US,United States,spotsource solution llc global human capital m...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0,CA,Canada,vend looking awesome new talent come join u yo...
17876,17877,NaN,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0,US,United States,weblinc ecommerce platform service provider fa...
17877,17878,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0,US,United States,provide full time permanent position many medi...
17878,17879,NaN,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0,NG,Nigeria,1 must fluent latest version corel amp adobe c...
17879,17880,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0,NZ,New Zealand,vend looking awesome new talent come join u yo...

# Testing code

### Get fraudulent records and get common words
> Classify the records as negative if contains 80 percent of the words 
### Get non fraudulent records and get common words
>Classify the records as positive if contains 80 percent of the words or less than 40 perent of fraudulent commone words
### Else
> Classify as Neutral

In [61]:
### THis is an example code to remind you of where you stopped
from nltk.probability import FreqDist

tokenized_text = ' '.join(df['preprocessed_column']).split()

# Calculate the frequency distribution of words
freq_dist = FreqDist(tokenized_text)

# Print the most common words and their frequencies
print("Most common words:")
for word, frequency in freq_dist.most_common(60):  # Change 20 to the desired number of common words
    print(f"{word}: {frequency}")

Most common words:
work: 35988
’: 35904
team: 35813
experience: 34910
company: 27965
service: 27209
customer: 25616
business: 23035
client: 19621
product: 19055
new: 17780
year: 17401
skill: 17025
management: 15591
development: 15267
amp: 15175
working: 14986
sale: 14643
project: 13868
technology: 13271
job: 13188
opportunity: 12891
people: 12783
solution: 12480
design: 12429
looking: 12195
communication: 12028
u: 11908
time: 11560
marketing: 11328
position: 10787
help: 10691
ability: 10677
candidate: 10307
process: 10294
support: 10038
environment: 9987
including: 9986
data: 9896
knowledge: 9838
software: 9653
need: 9589
office: 9550
professional: 9145
system: 9115
web: 9022
provide: 8940
employee: 8846
application: 8624
one: 8547
well: 8546
industry: 8483
quality: 8402
best: 8126
world: 7916
also: 7845
required: 7835
make: 7769
medium: 7723
based: 7608